cd ..
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_clear_Mod1_p-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_clear_Mod1_p-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_clear_Mod1_pop-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_clear_Mod1_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_clear_Mod1_size-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_clear_Mod1_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_clear_Mod2_peek-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_clear_Mod2_peek-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_clear_Mod2_pop-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_clear_Mod2_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_clear_Mod2_size-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_clear_Mod2_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_clear_Mod3_peek-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_clear_Mod3_peek-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_clear_Mod3_pop-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_clear_Mod3_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_clear_Mod3_s-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_clear_Mod3_s-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_clear_Mod3_size-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_clear_Mod3_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod1_isEmpty_Mod2_push-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod1_isEmpty_Mod2_push-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod2_peek_Mod1_size-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod2_peek_Mod1_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_clear_Mod1_isEmpty-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_clear_Mod1_isEmpty-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_clear_Mod1_push-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_clear_Mod1_push-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_clear_Mod1_size-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_clear_Mod1_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_clear_Mod2_pop-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_clear_Mod2_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_clear_Mod2_push-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_clear_Mod2_push-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_clear_Mod2_size-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_clear_Mod2_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_clear_Mod3_size-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_clear_Mod3_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_pop_Mod1_clear-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_pop_Mod1_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_pop_Mod1_isEmpty-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_pop_Mod1_isEmpty-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_pop_Mod1_size-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_pop_Mod1_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_pop_Mod2_clear-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_pop_Mod2_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_pop_Mod2_push-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_pop_Mod2_push-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_pop_Mod2_size-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_pop_Mod2_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_pop_Mod3_clear-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_pop_Mod3_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_pop_Mod3_size-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_pop_Mod3_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_push_Mod1_clear-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_push_Mod1_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_push_Mod1_pop-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_push_Mod1_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_push_Mod2_clear-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_push_Mod2_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_push_Mod2_peek-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_push_Mod2_peek-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_push_Mod2_pop-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_push_Mod2_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_push_Mod3_clear-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_push_Mod3_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_push_Mod3_peek-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_push_Mod3_peek-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6/Mod3_push_Mod3_pop-ruleValidator.csv -r Rules/FS6_A__sup_02-conf_1.csv -o A_fr_Mod3_push_Mod3_pop-ruleValidator.csv

call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_clear_Mod1_p-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_clear_Mod1_p-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_clear_Mod1_pop-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_clear_Mod1_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_clear_Mod1_size-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_clear_Mod1_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_clear_Mod2_peek-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_clear_Mod2_peek-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_clear_Mod2_pop-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_clear_Mod2_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_clear_Mod2_size-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_clear_Mod2_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_clear_Mod3_peek-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_clear_Mod3_peek-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_clear_Mod3_pop-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_clear_Mod3_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_clear_Mod3_s-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_clear_Mod3_s-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_clear_Mod3_size-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_clear_Mod3_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod1_isEmpty_Mod2_push-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod1_isEmpty_Mod2_push-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod2_peek_Mod1_size-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod2_peek_Mod1_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_clear_Mod1_isEmpty-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_clear_Mod1_isEmpty-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_clear_Mod1_push-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_clear_Mod1_push-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_clear_Mod1_size-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_clear_Mod1_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_clear_Mod2_pop-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_clear_Mod2_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_clear_Mod2_push-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_clear_Mod2_push-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_clear_Mod2_size-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_clear_Mod2_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_clear_Mod3_size-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_clear_Mod3_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_pop_Mod1_clear-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_pop_Mod1_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_pop_Mod1_isEmpty-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_pop_Mod1_isEmpty-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_pop_Mod1_size-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_pop_Mod1_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_pop_Mod2_clear-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_pop_Mod2_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_pop_Mod2_push-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_pop_Mod2_push-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_pop_Mod2_size-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_pop_Mod2_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_pop_Mod3_clear-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_pop_Mod3_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_pop_Mod3_size-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_pop_Mod3_size-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_push_Mod1_clear-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_push_Mod1_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_push_Mod1_pop-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_push_Mod1_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_push_Mod2_clear-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_push_Mod2_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_push_Mod2_peek-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_push_Mod2_peek-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_push_Mod2_pop-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_push_Mod2_pop-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_push_Mod3_clear-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_push_Mod3_clear-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_push_Mod3_peek-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_push_Mod3_peek-ruleValidator.csv
call python faultDetector.py -i ruleValidator-FS6B/Mod3_push_Mod3_pop-ruleValidator.csv -r Rules/FS6_B__sup_02-conf_1.csv -o B_fr_Mod3_push_Mod3_pop-ruleValidator.csv