cd ..

call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod1_isEmpty_Mod2_push.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod1_isEmpty_Mod2_push-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleVBlidator-FS12B -o Mod2_peek_Mod1_pop-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod2_peek_Mod1_push.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod2_peek_Mod1_push-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod2_peek_Mod1_size.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod2_peek_Mod1_size-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod2_peek_Mod2_clear.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod2_peek_Mod2_clear-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod2_peek_Mod2_pop.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod2_peek_Mod2_pop-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod2_peek_Mod2_push.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod2_peek_Mod2_push-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod2_peek_Mod2_size.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod2_peek_Mod2_size-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod2_peek_Mod3_size.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod2_peek_Mod3_size-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_clear_Mod1_isEmpty.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_clear_Mod1_isEmpty-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_clear_Mod1_push.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_clear_Mod1_push-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_clear_Mod1_size.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_clear_Mod1_size-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_clear_Mod2_peek.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_clear_Mod2_peek-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_clear_Mod2_pop.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_clear_Mod2_pop-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_clear_Mod2_push.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_clear_Mod2_push-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_clear_Mod2_size.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_clear_Mod2_size-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_clear_Mod3_peek.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_clear_Mod3_peek-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_clear_Mod3_size.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_clear_Mod3_size-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_pop_Mod1_clear.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_pop_Mod1_clear-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_pop_Mod1_isEmpty.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_pop_Mod1_isEmpty-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_pop_Mod1_size.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_pop_Mod1_size-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_pop_Mod2_clear.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_pop_Mod2_clear-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_pop_Mod2_peek.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_pop_Mod2_peek-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_pop_Mod2_push.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_pop_Mod2_push-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_pop_Mod2_size.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_pop_Mod2_size-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_pop_Mod3_clear.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_pop_Mod3_clear-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_pop_Mod3_peek.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_pop_Mod3_peek-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_pop_Mod3_size.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_pop_Mod3_size-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_push_Mod1_clear.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_push_Mod1_clear-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_push_Mod1_pop.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_push_Mod1_pop-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_push_Mod2_clear.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_push_Mod2_clear-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_push_Mod2_peek.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_push_Mod2_peek-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_push_Mod2_pop.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_push_Mod2_pop-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_push_Mod3_clear.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_push_Mod3_clear-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_push_Mod3_peek.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_push_Mod3_peek-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod3_push_Mod3_pop.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod3_push_Mod3_pop-
call python ruleValidator.py -i UniqueNewRows/unr-FS12/unr_BFS12_FS12FS__B_h_Mod1_isEmpty_Mod1_push.csv -r Rules/FS12_B__sup_02-conf_1.csv -f ruleValidator-FS12B -o Mod1_isEmpty_Mod1_push-